#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
set -x
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_65
export PATH=$JAVA_HOME/bin:$PATH
cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-1.12
export PATH=$GRADLE_HOME/bin:$PATH
sed -i.bak "s#SENTRY_DSN#$SENTRY_DSN#" app/src/main/resources/prod_logback.xml
mv app/src/main/resources/prod_logback.xml app/src/main/resources/logback.xml
./gradlew --no-daemon wrapper stage
mv app/build/libs/app.jar cruncher.jar
./gradlew --no-daemon clean
rm -Rf $GRADLE_USER_HOME/caches/*
