#!/bin/bash
set -x
VERSION=1.12
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-$VERSION ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir -p gradle
    wget http://services.gradle.org/distributions/gradle-$VERSION-bin.zip
    unzip gradle-$VERSION-bin.zip
    rm -f gradle-$VERSION-bin.zip
fi
