#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_65
export PATH=$JAVA_HOME/bin:$PATH
nohup java $JAVA_OPTS -Dserver.port=${OPENSHIFT_DIY_PORT} -Dserver.address=${OPENSHIFT_DIY_IP} -Ddatabase-pets.uri=${MONGOLAB_URI} -Dbackend.admin.username=${APP_USERNAME} -Dbackend.admin.password=${APP_PASSWORD} -jar $OPENSHIFT_REPO_DIR/cruncher.jar > ${OPENSHIFT_DIY_LOG_DIR}/cruncher.log 2>&1 &
