language: java
jdk:
- oraclejdk8
os:
- linux
services:
- mongodb
env:
  global:
  - SPRING_PROFILES_ACTIVE="unit-test"
before_install:
- chmod +x gradlew
install: "./gradlew :app:assemble"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack:
    secure: mh9wbK5q5Sb2tB6WqHJrLadlweqZn2pspCIipn2ecVfmlXiL9xCxRH8nXNvEEIfaRquQv3ak/l6RH2qYm0auyS6mhDKK/IKUDgRTIBCSfTyr9dSRaHVjD+YT3ZLFfdr5RJc3wbEyC8hjuSU8Fih+OP8a3rjfj/8BxhRHS2Prgk7QcyW2E2W8IfmbkFYUmMDvDN6WQ3tf6wVf+lmOJenjZTSXw+YPys2LMlIFPAZubqhdO6rlUIxNJdtUxWJrkGINMvl7YQOHGf90hDZ7KAmA9h0WpdZnF1iGncYIjoTMgl7Xj1zjnggI1wx/+B0cqjIfNUfEaTa3YdFKhmN2wqhGqvKShjODUSd25O9KPPEHDGyAXPsqsrqVx4rj1217Fo2MbdglmwtxWqr/8IzMb44q/nBMVWlb89O+s3Xe1GpPyuMRwrUxP/dQXSGIONznyzbjYW5pPFcSDEg675CiYUZShqHka2zq/MGiY5PDxBpHsL7wqCpHoWG8NFbIO7MShiLq6h7fy1+T+p3h0lu3/8N8aqGgvEiPAwlySkEaYgw27l5QQx4mJZstB9Dt0Pd1BgTB19VenHl5gp5iNayb7RLs4y/Ufgso/P+YuM3kRi9vn5YmeAKV2RRNKSR7e8iyjekUBHvggulF2SCBpcJnlPoRQlDvoIT1HlC/73jTB567/4s=
deploy:
  provider: openshift
  user: pets_admin@metplus.org
  password:
    secure: EHdoxslWp9Iwndpy8iVgBHXS7hZbq6tBPrkRvj0QcU/v9XKDvkMVKzuBaSnG9IJieaQqERlbS85KXGax7cf0ZX2Xl0tmFPS1XLxE//mLQF/3oM4g3FCo9SxAk3Ebsrn4t+JQr5Fu5c8krRnevNak3hwyNF5811eTCFcplb1Q2QCDtwDLDQGZEO6YW4NK5r4eGPEJ4Pqh9PNPyLKmSlT6rNEXkqETxYF8SBv8XAgUuCvRPAh0XMmX/zdi8GwMvTyDA9pYE5Xf8OYYQfh1RafF9RBztnfJc3mMtgGQwdRJP70MonNUbfHSrspiWOTtkyKPoPh8BNUPdETZzqmgRTkGIelzBjtQCPi0N42jJChcZ6rDRxMXFhhD/VCppmKDnKCJ07Sv5kkJv+zWU0sONLCmINkMLX/My56HgtkCH7qrrixoNVjCHVtaMnU2prqdJl4V+D+3a34qIU7lQLOyfbrN4PAt0MZcMoBj5c2R4NZtmplGkDcoHUHpNL1JpX/1zU6uYHWe+r3H9o5LDQxgPdwIaljsei3e0QGsND4KmEqoO1WvhNjCyrzsdgMAhwU94vtXtohp6T/zWviLW3GW7LE6R7Cf8LvOSolKnv2jB817I6oXc/iWtjBqtmzq66RPaxoHBmo6DfDNg6Jgu+PlwINddjcAaFxxxXEc3wtxXQlhcHE=
  app: cruncher
  domain: metpluspets
  on:
    branch: development
  deployment_branch: development
