language: java
jdk:
- oraclejdk8
os:
- linux
services:
- mongodb
env:
  global:
  - SPRING_PROFILES_ACTIVE="unit-test"
before_install:
- chmod +x gradlew
install: "./gradlew :app:assemble"
notifications:
  slack:
    rooms:
      secure: YI8mUkNlytqxJIJCELFTQJpobdCSZ+os33etwrXs2t86T8qLQ/F+WZgkKHFrCqzVaFGhgIhJ4HbKu3hcwurolMSfldbuUJp33n+ZXIGPZLVkloXorTwobJsqgcMH1x5sf3AwMtbV1mc+cBUl9dDaWBpp8ZkHG+5Zo468XWeDx4jjWNMO8i4uzpffLeKAxY0bfegFCF/nIIMZ1/20g51XEIT+sss6nQ+mvCTPjkJfnDDnig96mhDb/FOgJhNrPS6kDw/rsq4oRMGyQWixEP3v/N4Yz6fFJA4k66PVTBkLs1+o0ukMLY3+Y1EkzAUPHYkQhmS2JKK8gvVn9j308/NUt7MvoAt4Ki1GHolLAkYoUyTaxpJIg85BulpUJ2vlwGqpJXaohaUVzQo2o2JLEuJzGprUtIPJ50uGVoeedD8ObZgIMqdbx19BOKBbiuSdVSxYqGCQzO5JoavsrC/m2OsIBdqYYqZUWTKTeEAjtXrUkH3bJXQcNXv2e4old1JKiWjXwsmm7fRa6P6v9Y0cRd+uW8Qk3brH0n9wYfpsPdt2MytGjAHv1Zs4NTiUO36g0/btXAmv3V+fYRrcxXdnck0UoqjV3xABffXOsXBi6rNqqRB37jyzWdS5WB9A3w9w6pzkoGE/ZU8g2fuqPVCTxVFuHdATbTb2GoYs9G4P+mkWi4w=
