language: java
jdk:
- oraclejdk8
os:
- linux
services:
- mongodb
env:
  global:
  - SPRING_PROFILES_ACTIVE="unit-test"
before_install:
- chmod +x gradlew
install: "./gradlew :app:assemble"
notifications:
  slack:
    secure: EjMM/zu5eRVVZrWi/TO+2y/bKirJXMuSoirSfwEvIkmP6E+NPJVpTWVNr7r2NSoxAbc5s8zEt/HSmR7QgO9SMy9JP0zYs879lM3i3avB7NC844a3Mqju5gVOZjWGLZJnppmIKAskxtoQANTZqO7Ve7dBTYX9VhpRzcq6TvbWcNRaXG7o3HVtxWRG1dzamjwLDKVyfuO3MdhCQEpS8rvw0RZk6ouUPoaKFgqiosjvGG+NHwG58gijyxMvG6uT6KK1PIG8K+qgpiINLi8YlO181QO6GvsrNgOpHm708HdiBsq03L+Oo5fLXCudPEwRrSiJ02uu4XIQ+MxLJMuIRnl4bUTOMvLKentNMWCF0LOdvS1oIwv7wCAxj3CZWg/leHC9hwtQSlgWuCdMyns6SxH9qOHYaQIZFxddmxNuzq02SG6mXNeW+cvUSKfDAsdtoaQNuv976/m7FcRsSRiCx6GxN2o6NgtvTtURZoLLAN7o6Ft/vMkoWJnZr8kl7UrmoJaZC/xAR/XJgXVLeIHvrg2U5ZTj2BYu8vdvIRDjtAHWuhQ4j3iD7eGutsGXhrWaQ0gqpe/+32wnKzBu6oaaVyYKgZ55034wY7r2S+dmCm6y7z7zzEvFlpiPUYkYTqZ5i+DXp/Mtayl/9Tt1EPEW84c+XBXxjW1r0aW5aPnY1E160uI=
