language: java
jdk:
- oraclejdk8
os:
- linux
services:
- mongodb
env:
  global:
  - SPRING_PROFILES_ACTIVE="unit-test"
before_install:
- chmod +x gradlew
install: "./gradlew :app:assemble"
notifications:
  slack: agileventures:QOQsuy4HPehUbsQDpz0fNf3b
