FROM openjdk:8-jdk as builder
RUN mkdir -p /cruncher/app
WORKDIR /cruncher
COPY . /cruncher/app
RUN cd /cruncher/app && ./gradlew web:bootjar
RUN mv /cruncher/app/web/build/libs/web.jar /cruncher/cruncher.jar

FROM openjdk:8u181-jre-alpine3.8
RUN mkdir /cruncher/
COPY --from=builder /cruncher/app/launch_cruncher.sh /cruncher/
COPY --from=builder /cruncher/cruncher.jar /cruncher/
CMD /cruncher/launch_cruncher.sh
