spring:
    profiles.active: development

    log4j.logger: DEBUG
    log4j.logger.org.hibernate: ERROR
    log4j.logger.com.mongodb: SEVERE
    # Define the root logger with appender file
    log4j.rootLogger = DEBUG, FILE

    # Define the file appender
    log4j.appender.FILE=org.apache.log4j.FileAppender
    # Set the name of the file
    log4j.appender.FILE.File=C:\\log.out

    # Set the immediate flush to true (default)
    log4j.appender.FILE.ImmediateFlush=true

    # Set the threshold to debug mode
    log4j.appender.FILE.Threshold=debug

    # Set the append to false, overwrite
    log4j.appender.FILE.Append=false

    # Define the layout for file appender
    log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
    log4j.appender.FILE.layout.conversionPattern=%m%n
---
spring:
  profiles: development

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: mypassword
    keyStoreType: PKCS12
    keyAlias: tomcat

---
spring:
  profiles: production

server:
  port: 8443
  ssl:
    key-store:
    key-store-password:
    keyStoreType:
    keyAlias:
---
spring:
  profiles: unit-test

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: mypassword
    keyStoreType: PKCS12
    keyAlias: tomcat