spring:
    profiles.active: development

    log4j.logger: DEBUG
    log4j.logger.org.hibernate: ERROR
    log4j.logger.com.mongodb: SEVERE
    log4j.logger.org.apache: ERROR
    log4j.logger.org.metplus: DEBUG
logging.level.org.metplus: DEBUG


backend.admin.role: BACKEND_ADMIN

---

spring:
  profiles: development

server:
  port: 8443

backend:
  admin:
    username: backend_admin
    password: backendpassword
---
spring:
  profiles: production

server:
  port: 8443

backend:
  admin:
    username: ${username}
    password: ${password}

---
spring:
  profiles: unit-test

server:
  port: 8443

backend:
  admin:
    username: backend_admin
    password: backendpassword
