spring:
  profiles.active: development

logging.level: INFO
logging.level.org.hibernate: ERROR
logging.level.com.mongodb: ERROR
logging.level.org.springframework: INFO

---

spring:
  profiles: development

logging.level.org.metplus: DEBUG

server:
  port: 8443

backend:
  admin:
    username: backend_admin
    password: backendpassword

database-pets:
  username: testing_user
  password: testing_user
  name: resumeCruncher
  host: localhost
  port: 27017


---
spring:
  profiles: production

server:
  port: 8443

backend:
  admin:
    username: ${username}
    password: ${password}


logging.level.org.metplus: INFO

database-pets:
  name:
  host:
  port: 0
  username:
  password:
