spring:
  profiles.active: development

logging.level: INFO
logging.level.org.hibernate: ERROR
logging.level.com.mongodb: ERROR
logging.level.org.springframework: INFO

---

spring:
  profiles: development

logging.level.org.metplus: DEBUG

server:
  port: 8443

backend:
  admin:
    username: backend_admin
    password: backendpassword


---
spring:
  profiles: production

server:
  port: 8443

backend:
  admin:
    username: ${username}
    password: ${password}


logging.level.org.metplus: INFO

---

spring:
  profiles: test

backend:
  admin:
    username: backend_admin
    password: backendpassword