spring:
  profiles.active: development
---
spring:
  profiles: development

pets-db:
    name: expression_counter_db
    host: ds049651.mongolab.com
    port: 49651
    username: testing_user
    password: testing_user
---
spring:
  profiles: production

pets-db:
  name:
  host:
  port:
  username:
  password:
---
spring:
  profiles: unit-test

pets-db:
  name: expression_counter_db
  host: localhost
  port: 27017